// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string Department { get; set; }

    public DateTime? DateOfJoining { get; set; }

    public string ProfileName { get; set; }
}